name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 2:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add a Commit - 22f3001777@ds.study.iitm.ac.in
        run: |
          date >> daily_commit.log
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "22f3001777@ds.study.iitm.ac.in"
          git add daily_commit.log
          git commit -m "Automated daily commit"
          git push
