name: Daily Commit

on:
  schedule:
    - cron: '28 7 * * *'  # Runs daily at 7:28 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "22f3001777@ds.study.iitm.ac.in"

      - name: Add a Commit
        run: |
          date >> daily_commit.log
          git add daily_commit.log
          git commit -m "Automated daily commit"
          git push

